apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: user-management
data:
  NODE_ENV: production
  PORT: "5000"
  MONGODB_URI: mongodb://mongodb-service:27017/user-management
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  JWT_ACCESS_EXPIRY: 15m
  JWT_REFRESH_EXPIRY: 7d
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  OTP_EXPIRY: "300"
  OTP_LENGTH: "6"
  FRONTEND_URL: https://your-domain.com
  RATE_LIMIT_WINDOW: "15"
  RATE_LIMIT_MAX_REQUESTS: "100"
