apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: user-management
type: Opaque
stringData:
  JWT_ACCESS_SECRET: your-super-secret-jwt-access-key-production
  JWT_REFRESH_SECRET: your-super-secret-jwt-refresh-key-production
  SMTP_USER: your-email@gmail.com
  SMTP_PASSWORD: your-app-specific-password
  MONGODB_ROOT_PASSWORD: your-mongodb-password
